spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.apache.phoenix.queryserver.client.Driver
    url: jdbc:phoenix:thin:url=http://hadoop249:8765;serialization=PROTOBUF

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.dreamtail.springboot.phoenix.entity
